/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/algorithms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Algorithms */
        get: operations["list_algorithms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs"];
        put?: never;
        /** Create Job */
        post: operations["create_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Detail */
        get: operations["get_job_detail"];
        put?: never;
        post?: never;
        /** Delete Job Endpoint */
        delete: operations["delete_job"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Volume */
        get: operations["get_job_volume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/slice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Slice */
        get: operations["get_job_slice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/window-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Window Stats */
        get: operations["get_window_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort Job */
        post: operations["abort_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Job Result */
        get: operations["download_job_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Job Input */
        get: operations["download_job_input"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlgorithmId
         * @description Supported reconstruction algorithms.
         * @enum {string}
         */
        AlgorithmId: "direct_reconstruction" | "sense";
        /**
         * AlgorithmInfo
         * @description Algorithm metadata for the UI.
         */
        AlgorithmInfo: {
            id: components["schemas"]["AlgorithmId"];
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Default Params */
            default_params: components["schemas"]["DirectReconstructionParams"] | components["schemas"]["SenseParams"];
        };
        /**
         * AlgorithmsResponse
         * @description Available reconstruction algorithms.
         */
        AlgorithmsResponse: {
            /** Algorithms */
            algorithms: components["schemas"]["AlgorithmInfo"][];
        };
        /** Body_create_job */
        Body_create_job: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Pulseq File */
            pulseq_file?: string | null;
            /** Name */
            name?: string | null;
            /** @default direct_reconstruction */
            algorithm: components["schemas"]["AlgorithmId"];
            /** Params */
            params?: string | null;
        };
        /**
         * CreateJobResponse
         * @description Job creation response.
         */
        CreateJobResponse: {
            job: components["schemas"]["Job"];
        };
        /**
         * CsmAlgorithm
         * @enum {string}
         */
        CsmAlgorithm: "walsh" | "inati" | "none";
        /** DirectReconstructionParams */
        DirectReconstructionParams: {
            /** @default ismrmrd */
            trajectory_calculator: components["schemas"]["TrajectoryCalculator"];
            /** Pulseq Filename */
            pulseq_filename?: string | null;
            /** @default walsh */
            csm_algorithm: components["schemas"]["CsmAlgorithm"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            algorithm: "direct_reconstruction";
        };
        /**
         * DownloadFormat
         * @description Available download formats.
         * @enum {string}
         */
        DownloadFormat: "npy" | "nii" | "h5";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * Job
         * @description Persistent job metadata used by the API.
         */
        Job: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            status: components["schemas"]["JobStatus"];
            algorithm: components["schemas"]["AlgorithmId"];
            /** Params */
            params: components["schemas"]["DirectReconstructionParams"] | components["schemas"]["SenseParams"];
            /** Result Shape */
            result_shape: number[] | null;
            /** Available Formats */
            available_formats: components["schemas"]["DownloadFormat"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Input Filename */
            input_filename: string;
            /** Result Dataset */
            result_dataset: string;
            /**
             * Input Available
             * @default true
             */
            input_available: boolean;
            /**
             * Result Available
             * @default true
             */
            result_available: boolean;
            /** Log Messages */
            log_messages?: string[];
            /** Error */
            error?: string | null;
            /** Queue Task Id */
            queue_task_id?: string | null;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "started" | "finished" | "failed" | "deferred" | "scheduled" | "canceled" | "stopped";
        /**
         * JobsListResponse
         * @description Jobs list response.
         */
        JobsListResponse: {
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** SenseParams */
        SenseParams: {
            /** @default ismrmrd */
            trajectory_calculator: components["schemas"]["TrajectoryCalculator"];
            /** Pulseq Filename */
            pulseq_filename?: string | null;
            /** @default walsh */
            csm_algorithm: components["schemas"]["CsmAlgorithm"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            algorithm: "sense";
            /**
             * Iterations
             * @default 10
             */
            iterations: number;
        };
        /**
         * TrajectoryCalculator
         * @enum {string}
         */
        TrajectoryCalculator: "ismrmrd" | "cartesian" | "pypulseq";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WindowStatsResponse */
        WindowStatsResponse: {
            /** P01 */
            p01: number;
            /** P99 */
            p99: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_algorithms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlgorithmsResponse"];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListResponse"];
                };
            };
        };
    };
    create_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_job"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_volume: {
        parameters: {
            query?: {
                batch?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_slice: {
        parameters: {
            query: {
                orientation: string;
                index: number;
                batch?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_window_stats: {
        parameters: {
            query?: {
                batch?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindowStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_job_result: {
        parameters: {
            query?: {
                format?: components["schemas"]["DownloadFormat"];
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_job_input: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
